### PR TITLE
React calculator added

### PR DESCRIPTION
**Pull request by markandey1414**
Files added under the path "./pages/activities/components/".
app.js, index.css updated necessarily

### CODE REVIEW

**Comment by markandey1414** [comment]
Hello, kindly open the review under vercel so that I can see and resolve the errors.

**Comment by Ishwarendra** [comment]
Hi @markandey1414, Here are vercel logs
```
Failed to compile.
Module not found: Error: Can't resolve './activities/components/Wrapper' in '/vercel/path0/src'
Error: Command "npm run build" exited with 1
```

- You have imported your components with incorrect path. 
- Don't add calculator component in `App.js` Make a separate file for it in `pages/activities`. 
- Move other calculator related component from `pages/` to `components/activities/`. You can make a new directory for calculator inside it to keep everything organised.

**Comment by ken1000minus7** [comment]
@markandey1414 any updates?

**Comment by markandey1414** [comment]
I won't be able to work on this issue @ken1000minus7, apologies for all the trouble.

**Pull request closed without merging**
