### PR TITLE
Guess the flag added

### PR DESCRIPTION
**Pull request by SanidhyaSharma28**
can you please check i have added functionality of like 3 lifelines and 2 hints per guess you get 5 points if you guess without any hint 3 points if using one hint and one point if using both hints

### CODE REVIEW

**Comment by SanidhyaSharma28** [comment]
@Ishwarendra @ken1000minus7 can you check and tell if any updates required?

**Review by ken1000minus7 — COMMENTED** [review]
I would say add a button to submit as well  and also add a restart button at the end of the game to restart it

**Comment by ken1000minus7** [comment]
Also fix the size of the image displayed, as the elements keep on shifting when images change

**Comment by SanidhyaSharma28** [comment]
@Ishwarendra @ken1000minus7 can you check ??

**Comment by Ishwarendra** [comment]
@SanidhyaSharma28 add a submit button beside the input box for submitting answer. Keep it disabled if user hasn't typed anything in the box.

**Comment by SanidhyaSharma28** [comment]
Can You please check 🥺 @Ishwarendra @ken1000minus7

**Review by Ishwarendra — APPROVED** [review]
LGTM.. good work

**Comment by SanidhyaSharma28** [comment]
@Ishwarendra  is there any other issue i can work on ???  except the movable tic tac toe

**Comment by Ishwarendra** [comment]
@SanidhyaSharma28 You can suggest any activity or game you want to add. You can raise the issue for that, we will assign that to you

**Pull request merged**
