### PR TITLE
Change Navbar

### PR DESCRIPTION
**Pull request by sergomen**
Hi! I changed Navbar:
Screenshot_1111
Now it looks like:
Screenshot_4
opensource_acmfun_navigation

Can you check it, please?

### CODE REVIEW

**Review by ken1000minus7 — COMMENTED** [review]
The navbar looks great but the width of the rest of content is restricted to width of the navbar right now (probably because of changes to body in `Navbar.css` )  can u try fixing this? Also, there are conflicts in `Navbar.js` , resolve them as well

**Comment by sergomen** [comment]
> The navbar looks great but the width of the rest of content is restricted to width of the navbar right now (probably because of changes to body in `Navbar.css` ) can u try fixing this? Also, there are conflicts in `Navbar.js` , resolve them as well

Sure. I will try to fix them. This is my first pull request for an open source project. Won't I lose my changes if I pull the repo? Or do I need to fetch it?

**Comment by ken1000minus7** [comment]
You won't lose your changes when you pull, all non conflicting will be pulled normally and for conflicting files auto merge will be performed from where u can resolve the conflicts that appear, u can search up on how to resolve conflicts

**Review by ken1000minus7 — APPROVED** [review]
Lgtm gw, thx for your contribution

**Comment by sergomen** [comment]
> Lgtm gw, thx for your contribution

Thank you too :)

**Pull request merged**
