### PR TITLE
Updated the definitions page to show a list of definitions

### LINKED ISSUE #38: Display multiple definitions
currently only the first definition is displayed in get definitions activity, display a list of definitions

### PR DESCRIPTION
**Pull request by IrfanSalim**
closes #38 

image

### CODE REVIEW

**Comment by ken1000minus7** [comment]
Seems good but can u try to improve the ui of the cards?

**Comment by IrfanSalim** [comment]
> Seems good but can u try to improve the ui of the cards?

You have something specific in mind?

**Comment by ken1000minus7** [comment]
Not really, upto your imagination, just something better than simple text

**Comment by IrfanSalim** [comment]
@ken1000minus7 check if its fine

**Review by ken1000minus7 — APPROVED** [review]
Lgtm, gw!

**Pull request merged**
