### PR TITLE
Add logo for acm-fun

### PR DESCRIPTION
**Pull request by sergomen**
image

### CODE REVIEW

**Comment by sergomen** [comment]
After the PR I saw some conflicts. After that I pulled the repo. And merged conflicts. But it erased my changes and I returned it pressing "Ctrl+Z".
But also it shows mistake.
`SyntaxError: D:\Projects\OpenSource\acm-fun\src\components\common\Navbar.js: Unexpected token (64:1)

  62 |       <div className="navbar-wrapper">
  63 |         <div className="navbar-root">
> 64 | <<<<<<< HEAD
     |  ^
  65 |             <div className="navbar-heading">`

Can you help me to resolve this issue?

**Comment by sergomen** [comment]
If someday you want to create dark/light mode, I prepared dark and light logos for acm-fun
logo-acm-fun-dark
logo-acm-fun-white

**Comment by Ishwarendra** [comment]
> pressing "Ctrl+Z".

You need to remove the merge conflict markers. VS code shows the `conflicted` files in red. When you open them you will see `Open in Merge Editor` (or similar) button on bottom-right. Using that, you can resolve conflicts easily.

**Comment by sergomen** [comment]
> > pressing "Ctrl+Z".
> 
> You need to remove the merge conflict markers. VS code shows the `conflicted` files in red. When you open them you will see `Open in Merge Editor` (or similar) button on bottom-right. Using that, you can resolve conflicts e

**Comment by Ishwarendra** [comment]
Can we make it little better. It doesn't really match the existing content.

**Review by Ishwarendra — CHANGES_REQUESTED** [review]
For inspiration purpose, it should be something on the lines of this image, but with something extra denoting the fun-activity and games.

**Comment by sergomen** [comment]
or something like this:
image

**Comment by sergomen** [comment]
I added different logos, put them in the root:
logo.svg -> this is default right now.
acmlogo.png
acmlogo.svg
logoacm.png

**Comment by Ishwarendra** [comment]
@sergomen Let's go with second one. Update the logos path for `tab`, `navbar`. After that we will merge the PR

**Comment by sergomen** [comment]
@Ishwarendra, can you accept it pls?

**Comment by Ishwarendra** [comment]
@sergomen By second one I meant the circular one. Will merge the PR, just fix this.

**Comment by sergomen** [comment]
@Ishwarendra. I have changed.

**Review by Ishwarendra — APPROVED** [review]
Lgtm

**Pull request merged**
