### PR TITLE
Meme generator #13

### PR DESCRIPTION
**Pull request by GauravGupta993**
#13 Made a basic Meme Generator

### CODE REVIEW

**Comment by Ishwarendra** [comment]
Hi @GauravGupta993 this looks good but can you please update the input box so it looks a little nice.. Also add some spacing between meme and input box.

**Comment by GauravGupta993** [comment]
Will do so

**Comment by ken1000minus7** [comment]
Also use some other image for the icon of meme activity

**Comment by GauravGupta993** [comment]
> Also use some other image for the icon of meme activity

Will do so and will work on it's css.

**Pull request closed without merging**
