### PR TITLE
check that all number used are different in magic square game

### LINKED ISSUE #35: Add a button to validate magic square
- Currently user can only enter the number in magic square but cannot validate automatically whether the square is correct or not. 
- Also add logic to check that all $9$ numbers used are different. If they are not show a small red message above square for the same.

### PR DESCRIPTION
**Pull request by ChetanPatil12**
Fixes #35 
this PR will  check that all numbers used are different.

### CODE REVIEW

**Comment by Ishwarendra** [comment]
Hi @ChetanPatil12 add validation logic after all squares have been filled as well.

**Comment by ChetanPatil12** [comment]
added that feature

**Comment by Ishwarendra** [comment]
@ChetanPatil12 Make the text smaller. Rest lgtm.

image

**Comment by ChetanPatil12** [comment]
made the error text smaller to 30 px

**Comment by Ishwarendra** [comment]
@ChetanPatil12 Add something to clear a particular box and clear (reset) the entire board. Also there are some conflicts in `package-lock.json`. Take pull and fix them as well.

**Comment by ChetanPatil12** [comment]
i think conflict is resolved now

**Comment by Ishwarendra** [comment]
@ChetanPatil12 there are conflicts in `MagicSquares.js` now. Please check that once. Rest looks good.

**Comment by ChetanPatil12** [comment]
can you check now

**Review by Ishwarendra — APPROVED** [review]
Good work @ChetanPatil12

**Pull request merged**
