### PR TITLE
Arceen: Fortune and Random header not showing fix

### PR DESCRIPTION
**Pull request by Arceen**
**Fixes**
Fixes both Fortune card and RandomQuote headers from Issue: #43 
image
image

### CODE REVIEW

**Comment by Ishwarendra** [comment]
Fix the same issue for home page as well.
image

There is 1 div containing text `Home` which is covered by navbar.

**Comment by Ishwarendra** [comment]
@Arceen don't add `margin-top` to activity components. I see that you have added `margin-top` to fortune carrd. The navbar should take its space and all the components should be below it.

**Comment by Arceen** [comment]
@Ishwarendra So I can change the navbar component but not the activity component?

**Comment by Arceen** [comment]
@Ishwarendra Can you check if there's any issue now?

**Review by Ishwarendra — APPROVED** [review]
Good work @Arceen.

**Pull request merged**
